### ISSUE TITLE
Problem while starting job in Jenkins

### ISSUE THREAD

**Issue by Riffat1984** [browserstack/browserstack-local-java#29]
Hi,
I am having problem while starting the job. When I click the option Browserstacklocal and give path then i get following excpetion:

[BrowserStack] Local: Starting BrowserStack Local...
FATAL: Cannot run program "resources/browserDrivers/BrowserStackLocal": error=2, No such file or directory
ERROR: Failed to parse POMs
java.io.IOException: java.io.IOException: error=2, No such file or directory
	at com.browserstack.automate.ci.jenkins.BrowserStackBuildWrapper.setUp(BrowserStackBuildWrapper.java:61)
	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.doRun(MavenModuleSetBuild.java:667)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
	at hudson.model.Run.execute(Run.java:1727)
	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:543)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	at com.browserstack.local.Local.runCommand(Local.java:199)
	at com.browserstack.automate.ci.jenkins.local.JenkinsBrowserStackLocal.runCommand(JenkinsBrowserStackLocal.java:106)
	at com.browserstack.local.Local.start(Local.java:66)
	at com.browserstack.automate.ci.jenkins.local.JenkinsBrowserStackLocal.start(JenkinsBrowserStackLocal.java:65)
	at com.browserstack.automate.ci.jenkins.local.JenkinsBrowserStackLocal$1.call(JenkinsBrowserStackLocal.java:79)
	at com.browserstack.automate.ci.jenkins.local.JenkinsBrowserStackLocal$1.call(JenkinsBrowserStackLocal.java:76)
	at hudson.remoting.LocalChannel.call(LocalChannel.java:45)
	at com.browserstack.automate.ci.jenkins.local.JenkinsBrowserStackLocal.start(JenkinsBrowserStackLocal.java:76)
	at com.browserstack.automate.ci.jenkins.BrowserStackBuildWrapper$AutomateBuildEnvironment.startBrowserStackLocal(BrowserStackBuildWrapper.java:179)
	at com.browserstack.automate.ci.jenkins.BrowserStackBuildWrapper.setUp(BrowserStackBuildWrapper.java:58)
	... 6 more

**Comment by fmattheus** [comment]
See for example, this link:
https://github.com/nodejs/node/issues/6252
