### ISSUE TITLE
Error starting browerstack local

### ISSUE THREAD

**Issue by HesterLyons** [browserstack/browserstack-local-java#37]
## Expected Behavior

Given that I have a correct access key
When I start browerstack local
Then the browserstack local object should start successfully

## Actual Behavior

At line 41 of SearchSteps.java (l.start(options) an error is thrown: 
`org.json.JSONException: JSONObject["message"] is not a JSONObject.`
        `at org.json.JSONObject.getJSONObject(JSONObject.java:640)`
        `at com.browserstack.local.Local.start(Local.java:80)`
        `at com.browserstack.stepdefs.SearchSteps.setUp(SearchSteps.java:41)`
        `...`

## Steps to Reproduce the Problem

  1. Download the repository and extract
  2. Open command prompt or git bash in the extracted folder
  3. run `mvn install -Dbrowser=chrome -Dlocal=true` 

## browserstack local arguments

I have run the repository out of the box and changed no settings. I know that my Browserstack access credentials are correct and non-local tests run OK.

## Platform details
 
  1. browserstack-local-java version: 1.0.1
  2. java version: 1.8
  3. os type and version: Windows 10

## Details

the command Local.start() does not appear to function correctly and throws an error when invoked. The function new Local(); works OK and returns an object. The hashmap contains the correct elements.

**Comment by ramapriyamk** [comment]
I am seeing the same issue when I ran the example Class  as well separately just as a Java class:
Exception in thread "main" org.json.JSONException: JSONObject["message"] is not a JSONObject.
	at org.json.JSONObject.getJSONObject(JSONObject.java:640)
	at com.browserstack.local.Local.start(Local.java:80)
	at BrowserStackLocalExample.main(BrowserStackLocalExample.java:36)

For the following lines:
                    l = new Local();
		    HashMap<String, String> options = new HashMap<String, String>();
		    options.put("key", access_key);
		    **l.start(options); //Above mentioned error is thrown at this line**


I have tried with the following browserstack local versions:
1.0.3,1.0.2, 1.0.1, 1.0.0
My Browserstack access credentials are correct and non-local tests ran without any connectivity issues.

### **Platform Details:**
1) Maven - 3.3.9
2) Browsertack local dependency added in POM:
<dependency>
	<groupId>com.browserstack</groupId>
	<artifactId>browserstack-local-java</artifactId>
	<version>1.0.0</version>
</dependency>

### UPDATE:****
When I tried with Browserstack Local version 0.3.0, then the following error message is thrown:
Exception in thread "main" com.browserstack.local.LocalException: Disconnected
	at com.browserstack.local.Local.start(Local.java:78)

After careful debugging, I found
There is some issue at these lines inside the Local.class:
protected LocalProcess runCommand(List<String> command) throws IOException {
        ProcessBuilder processBuilder = new ProcessBuilder(command);
        final Process process = processBuilder.start();
May the right list of commands are not passed to the processbuilder.

**Comment by ramapriyamk** [comment]
After some more analysis, I found the following method in Local.class file to run the command , even when we ran it manually from command line it throws the same error:

 _private void makeCommand(Map<String, String> options, String opCode) {
        command = new ArrayList<String>();
        command.add(binaryPath);
        **command.add("-d");
        command.add(opCode);**
        command.add("--key");
        command.add(options.get("key"));_

In the above method if we remove the two lines and run then I think the local test might get enabled (though not sure what else might break)

manually running this command from source directory:
![image](https://user-images.githubusercontent.com/33444677/52370203-2a0acf80-2a07-11e9-8535-b463114e4957.png)

Just by running- 
BrowserStackLocal.exe -- key <yourAccessKeyValue>

The local connection is established without issues.

**Comment by artemklimenkov-qa** [comment]
I am seeing the same issue. Any updates on this?

**Comment by RohanImmanuel** [comment]
@artemklimenkov-qa could you confirm if you are encountering the same error with browserstack local v8.0

https://www.browserstack.com/local-testing/releases/v8.0

**Comment by schurik** [comment]
I get the same error even with the latest release v8.0.1.
I am starting Browserstack Local in a linux container running in OpenShift.
This issue appears since 25. May. before we had no problems.

here is the error :

Caused by: org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
--
  | at org.json.JSONTokener.syntaxError(JSONTokener.java:433) ~[json-20160212.jar!/:na]
  | at org.json.JSONObject.<init>(JSONObject.java:195) ~[json-20160212.jar!/:na]
  | at org.json.JSONObject.<init>(JSONObject.java:319) ~[json-20160212.jar!/:na]
  | at com.browserstack.local.Local.start(Local.java:78) ~[browserstack-local-java-1.0.3.jar!/:na]
